// <auto-generated />
namespace EF_examples_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_lastname_to_student : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_lastname_to_student));
        
        string IMigrationMetadata.Id
        {
            get { return "202206010936049_Add_lastname_to_student"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
